version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: instagram_telegram_mongodb_simple
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: instagram_telegram_chat
    volumes:
      - mongodb_data_simple:/data/db
      - ./docker/mongo-init-simple.js:/docker-entrypoint-initdb.d/mongo-init-simple.js:ro
    command: mongod --auth --bind_ip_all

volumes:
  mongodb_data_simple:
    driver: local 