version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: instagram_telegram_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: instagram_telegram_chat
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - instagram_telegram_network

  # Optional: MongoDB Express (web-based admin interface)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: instagram_telegram_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    networks:
      - instagram_telegram_network

volumes:
  mongodb_data:
    driver: local

networks:
  instagram_telegram_network:
    driver: bridge 